### ISSUE TITLE
Grafana [ERR]: Failed to upgrade legacy queries Datasource […] was not found

### ISSUE THREAD

**Issue by BabyFnord** [Kraego/OpenDTU-Grafana-Howto#3]
Hey @Kraego,

erst mal danke für dein OpenDTU-Grafana-Howto! Ich nutze die Kette MQTT-InfluxDB-Telegraf-Grafana auf einem hosted-shared-system, bin aber so weit, dass in der InfluxDB WebGUI → Data Explorer Werte angezeigt werden. In Grafana ist das Dashboard JSON geladen und die Inverter-SN eingetragen, jedoch meldet Grafana:
```
Templating
Failed to upgrade legacy queries Datasource ccdc09e4-b747-4e37-a3f9-aed28da7bab5 was not found

Templating
Template variable service failed Datasource ccdc09e4-b747-4e37-a3f9-aed28da7bab5 was not found
```
Meine Frage ist: 
Worauf bezieht sich diese `uid`, die im JSON 14x in diesem Block referenziert ist
```
      "datasource": {
        "type": "influxdb",
        "uid": "ccdc09e4-b747-4e37-a3f9-aed28da7bab5"
```
und falls die an die eigene Umgebung angepasst werden muss (was nicht im Tutorial steht), wo finde ich meine?

Danke so weit,
BF

**Comment by Kraego** [comment]
Hi,
danke für den Hinweis. Die uid bezieht sich auf deine influx db die musst du in grafana noch adden, werde das noch im tutorial hinzufügen.

**Comment by Kraego** [comment]
Tutorial upgedated
