### ISSUE TITLE
Sektion Downsampling Dashboard-Variable im How-to

### ISSUE THREAD

**Issue by BabyFnord** [Kraego/OpenDTU-Grafana-Howto#4]
Hey @Kraego,

zwei kleine Vorschläge:
Unter https://github.com/Kraego/OpenDTU-Grafana-Howto/blob/main/OpenDTUGrafana.md#create-a-query-variable-to-select-correct-bucket-depending-on-range-selection-grafana steht, wie die Dashboard-Variable für die `downsampled data` angelegt wird. Diese Variable ist bereits als `telegraf_all` angelegt, wenn man das [JSON des Dashboards](https://github.com/Kraego/OpenDTU-Grafana-Howto/blob/main/PV%20Station-1684694694468.json) importiert hat. Die Anleitung suggeriert aber, diese Variable abschließend noch anzulegen.

Bei dem Weg, für https://github.com/Kraego/OpenDTU-Grafana-Howto/blob/main/OpenDTUGrafana.md#influx-data-optimization---optional könnte es besser heißen (safe =! save):
`This section describes how to downsample old dataframes in your buckets, which saves memory and enables you to monitor several years back.`

_Speaking of several years back:_ Falls ich es nicht übersehen habe, werden die Daten nach dieser Anleitung nur 366 Tage gespeichert. Wenn mensch sich die Daten über den Lauf von zwei Jahren anschauen wollen würde, wäre das der richtige Weg?:
`influx bucket create -o "[YOUR ORGANIZATION]" -n telegraf/2years --retention 104w  --shard-group-duration 7d`
+
```
cat <<EOT > telegraf_downsample_2years
option task = {name: "telegraf_downsample_2years", every: 6h}

from(bucket: "telegraf/day")
    |> range(start: -task.every)
    |> aggregateWindow(every: 6h, fn: mean)
    |> to(org: "[YOUR ORGANIZATION]", bucket: "telegraf/2years")
EOT
influx task create -org "[YOUR ORGANIZATION]" -f telegraf_downsample_2years
```

Ciao, BF

**Comment by Kraego** [comment]
Danke für die Hints, habe bei meiner Instanz die Retention vom Year bucket auf 5 Jahre erhöht. Den Part mit der Scopevariable hab ich auch ergänzt. Nochmals danke. Cu
