### ISSUE TITLE
How to Grafana Total power production ?

### ISSUE THREAD

**Issue by madjuju** [Kraego/OpenDTU-Grafana-Howto#5]
<img width="1273" alt="image" src="https://github.com/Kraego/OpenDTU-Grafana-Howto/assets/5285199/e06f242f-16c9-4d4c-b186-37b041f8b839">
Could you help how to get the value ? in Grafana ?

**Comment by Kraego** [comment]
Have you done the howto? What is your specific question or problem?

**Comment by madjuju** [comment]
l ask how to get the value 41,7 w from influx to grafana

**Comment by Kraego** [comment]
You add your influx db as Datasource:
![image](https://github.com/Kraego/OpenDTU-Grafana-Howto/assets/71735135/ba568e12-0626-42d4-86db-d3d1e7148f73) - remember to select `flux` as query language.

Then you can query the value:
```
from(bucket: "${telegraf_all}")
  |> range(start: v.timeRangeStart, stop:v.timeRangeStop)
  |> filter(fn: (r) => r._measurement =~ /mqtt*/)
  |> filter(fn: (r) => r._field == "yieldtotal")
  |> filter(fn: (r) => r.channel == "0")
  |> truncateTimeColumn(unit: 5m)
  |> last()
```

the truncate is used to align the timeframes of your influxDB if you have multiple inverters, so it could be skipped if you just have one.

**Comment by madjuju** [comment]
Hello it give me only for 1 M
inverter but l have 3 inverter , l try to get the sum value off all inverters. 
<img width="1138" alt="image" src="https://github.com/Kraego/OpenDTU-Grafana-Howto/assets/5285199/7a6f86b0-bdee-4a4f-9c86-692effba21c7">

**Comment by Kraego** [comment]
with the query above you get all timeframes with yieldTotal, you can sum it up with a transformation in grafana:
![image](https://github.com/Kraego/OpenDTU-Grafana-Howto/assets/71735135/58a0e009-4091-4519-b2e9-94e52f8c377f)

**Comment by madjuju** [comment]
Merci
